name: Docker Image CI

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '*'

jobs:

  build:
    name: Build and Publish Image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Log in to Docker Hub
      run: echo "$DOCKER_PASSWORD" | docker login --username="${DOCKER_USERNAME}" --password-stdin
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Build the Docker image
      run: docker build -t junctionldn/nginx-php-base . --file Dockerfile 
    - name: Tag with run number
      run: docker tag junctionldn/nginx-php-base junctionldn/nginx-php-base:${GITHUB_RUN_NUMBER}
    - name: Tag with version
      run: docker tag junctionldn/nginx-php-base junctionldn/nginx-php-base:${GITHUB_REF_NAME}
    - name: Publish to Docker Hub
      run: docker push junctionldn/nginx-php-base
