name: Docker Image CI

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '*'

jobs:

  build:
    name: Build and Publish Image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: junctionldn/nginx-php-base
    - name: Log in to Docker Hub
      run: echo "$DOCKER_PASSWORD" | docker login --username="${DOCKER_USERNAME}" --password-stdin
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
